// <auto-generated />
namespace DC2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class descriptivenameformigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(descriptivenameformigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202412032109023_descriptive-name-for-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
